trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
      - bash: echo 'Build the Job'
- stage: QADeploy
  jobs:
  - deployment: QADeploy
    environment: QA
    strategy:
      runOnce:
        deploy:
         steps:
           - bash: echo 'Build Job for QA'