trigger:
- main

pool:
  vmImage: $(operatingSystem)

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
      - bash: echo 'Build the Job'
- stage: QAJob
  jobs:
  - deployment: QAJobDeploy
    environment: QAEnv
    strategy:
      runOnce:
        deploy:
         steps:
           - bash: echo 'Build Job for QA'